# Generated by Django 3.2.25 on 2024-06-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
    ]
